"""
Django settings for awmproject project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import socket
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

try:
    with open(os.path.join(BASE_DIR, 'secret_key.txt')) as f:
        SECRET_KEY = f.read().strip()
except FileNotFoundError:
    raise Exception("Secret key missing. Please include secret key in base directory.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'world',
    'map',
    'django.contrib.gis',
    #'crispy_forms',
    #'leaflet'
]

#CRISPY_TEMPLATE_PACK = 'bootstrap4'

#CRISPY_FAIL_SILENTLY = not DEBUG

#LEAFLET_CONFIG = {
#         'DEFAULT_CENTER': (53.0, -8.0),
#         'DEFAULT_ZOOM': 6,
#         'MIN_ZOOM': 3,
#         'MAX_ZOOM': 18,
#         'RESET_VIEW': False,
#         'SCALE': None,
#         'OPACITY': 0.5,
#        }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'awmproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awmproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'gis',
        'HOST': 'postgis',
        'USER': 'docker',
        'PASSWORD': 'docker',
        'PORT': '5432',
    }
}

#GDAL_LIBRARY_PATH = r'C:\Users\dfega\miniconda3\envs\awm_env\Library\bin\gdal.dll'

import os

if socket.gethostname() != "HPLaptop":
    GDAL_LIBRARY_PATH = '/opt/conda/envs/awm_env/lib/libgdal.so'
    os.environ['PROJ_LIB'] = '/opt/conda/envs/awm_env/share/proj'
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': 'gis',
            'HOST': 'postgis',
            'USER': 'docker',
            'PASSWORD': 'docker',
            'PORT': '5432',
        }
    }
else:
    GDAL_LIBRARY_PATH = r'C:\Users\dfega\miniconda3\envs\awm_env\Library\bin\gdal.dll'
    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': 'gis',
            'HOST': 'localhost',
            'USER': 'docker',
            'PASSWORD': 'docker',
            'PORT': '5432',
        }
    }

#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Set DEPLOY_SECURE to True only for LIVE deployment
if socket.gethostname() == "HPLaptop":
    DATABASES["default"]["HOST"] = "localhost"
    #DATABASES["default"]["PORT"] = 5432
    DEBUG = True
    TEMPLATES[0]["OPTIONS"]["debug"] = True
    ALLOWED_HOSTS = ['*', ]
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
else:
    DATABASES["default"]["HOST"] = "postgis"
    #DATABASES["default"]["PORT"] = 5432
    DEBUG = False
    TEMPLATES[0]["OPTIONS"]["debug"] = False
    ALLOWED_HOSTS = ['.dfegan.xyz', 'localhost', 'dfegan.xyz']
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True