# Generated by Django 5.1.4 on 2024-12-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab9', '0005_alter_counties_attributio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counties',
            name='logainm_re',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='name_ga',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='name_tag',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='osm_timest',
            field=models.CharField(max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='osm_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='counties',
            name='t_ie_url',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
