# Generated by Django 5.1.4 on 2024-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_alter_place_amenity_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='amenity',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
